
DROP SEQUENCE MOVIE_SEQ;
DROP TABLE MOVIE;

CREATE TABLE MOVIE
(
    MOVIESEQ      NUMBER            NOT NULL, 
    MOVIETITLE    VARCHAR2(200)     NULL, 
    RATING        VARCHAR2(20)      NULL, 
    GENRE         VARCHAR2(200)     NULL, 
    TIME          VARCHAR2(2000)    NULL, 
    PUPDATE       VARCHAR2(200)     NULL, 
    MOVIESTATE    VARCHAR2(200)     NULL, 
    DIRECTOR      VARCHAR2(200)     NULL, 
    ACTOR         VARCHAR2(2000)    NULL, 
    IMGURL        VARCHAR2(2000)    NULL, 
    CODE          VARCHAR2(200)     NULL, 
    CONSTRAINT MOVIE_PK PRIMARY KEY (MOVIESEQ)
);


CREATE SEQUENCE MOVIE_SEQ
START WITH 1
INCREMENT BY 1;


-- UPDATETOEND확인용 더미 데이터
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'반지의 제왕','9.3','판타지','180분','2019.01.22','상영작','김민엽','김민엽','AAA','AAA');
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'반지의 제왕2','9.3','판타지','180분','2019.01.22','상영작','김민엽','김민엽','AAA','AAA');
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'반지의 제왕3','9.3','판타지','180분','2019.01.22','상영작','김민엽','김민엽','AAA','AAA');


SELECT * FROM MOVIE;

DELETE FROM MOVIE WHERE MOVIESEQ >50

UPDATE MOVIE SET MOVIESTATE='상영작' WHERE MOVIESEQ = 43

alter sequence MOVIE_SEQ increment by 7;



