DROP TABLE USERS;
DROP TABLE CHATTING;
DROP TABLE MATCHING;


CREATE TABLE USERS(
    USERSEQ           NUMBER            NOT NULL, 
    USERID            VARCHAR2(200)     NULL, 
    USERPW            VARCHAR2(200)     NULL, 
    USERNAME          VARCHAR2(200)     NULL, 
    USERPROFILE       VARCHAR2(200)     NULL, 
    USERSEX           VARCHAR2(200)     NULL, 
    USERAGE           VARCHAR2(200)     NULL, 
    USERADDRESS       VARCHAR2(200)     NULL, 
    USEREMAIL         VARCHAR2(200)     NULL, 
    USEREMAILHASH     VARCHAR2(2000)    NULL, 
    USEREMAILCHECK    VARCHAR2(200)     NULL, 
    USERTEATHER1      NUMBER            NULL, 
    USERTEATHER2      NUMBER            NULL, 
    USERTEATHER3      NUMBER            NULL, 
    USERGRADE         VARCHAR2(200)     NULL, 
    CONSTRAINT USER_PK PRIMARY KEY (USERSEQ)
);




CREATE TABLE CHATTING(
    CHATSEQ        NUMBER            NOT NULL, 
    USERSEQ1       NUMBER            NOT NULL, 
    USERSEQ2       NUMBER            NOT NULL, 
    CHATCONTENT    VARCHAR2(2000)    NOT NULL, 
    CHATDATE       DATE              NOT NULL, 
    CHATCHECK      VARCHAR2(20)      NOT NULL, 
    CONSTRAINT CHATTING_PK PRIMARY KEY (CHATSEQ)
);
ALTER TABLE Movie-Matching.CHATTING
    ADD CONSTRAINT FK_CHATTING_USERSEQ1_USERS_USE FOREIGN KEY (USERSEQ1)
        REFERENCES USERS (USERSEQ);

ALTER TABLE Movie-Matching.CHATTING
    ADD CONSTRAINT FK_CHATTING_USERSEQ2_USERS_USE FOREIGN KEY (USERSEQ2)
        REFERENCES USERS (USERSEQ);
        
        
        
CREATE TABLE MATCHING(
    MATCHINGSEQ          NUMBER          NOT NULL, 
    MATCHINGWRITER       NUMBER          NULL, 
    MATCHINGAPPLICANT    NUMBER          NULL, 
    MATCHINGSTATE        VARCHAR2(20)    NULL, 
    WRITERNOTICE         VARCHAR2(20)    NULL, 
    APPLICANTNOTICE      VARCHAR2(20)    NULL, 
    MATCHINGDATE         DATE            NULL, 
    SELECTEDAPPLICANT    VARCHAR2(20)    NULL, 
    CONSTRAINT MATCHING_PK PRIMARY KEY (MATCHINGSEQ)
);