DROP TABLE USERS;
DROP TABLE CHATTING;
DROP TABLE MATCHING;
DROP TABLE COIN;
DROP TABLE REVIEWBOARDCOMENT;
DROP TABLE REVIEWBOARD;

DROP SEQUENCE REVIEWBOARDCOMENT_SEQ;
DROP SEQUENCE REVIEWBOARD_SEQ;

CREATE TABLE USERS(
    USERSEQ           NUMBER            NOT NULL, 
    USERID            VARCHAR2(200)     NULL, 
    USERPW            VARCHAR2(200)     NULL, 
    USERNAME          VARCHAR2(200)     NULL, 
    USERPROFILE       VARCHAR2(200)     NULL, 
    USERSEX           VARCHAR2(200)     NULL, 
    USERAGE           VARCHAR2(200)     NULL, 
    USERADDRESS       VARCHAR2(200)     NULL, 
    USEREMAIL         VARCHAR2(200)     NULL, 
    USEREMAILHASH     VARCHAR2(2000)    NULL, 
    USEREMAILCHECK    VARCHAR2(200)     NULL, 
    USERTEATHER1      NUMBER            NULL, 
    USERTEATHER2      NUMBER            NULL, 
    USERTEATHER3      NUMBER            NULL, 
    USERGRADE         VARCHAR2(200)     NULL, 
    CONSTRAINT USER_PK PRIMARY KEY (USERSEQ)
);
INSERT INTO USERS VALUES(1,'오세현','dhtpgus',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO USERS VALUES(2,'유저','dbwj',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);



CREATE TABLE CHATTING(
    CHATSEQ        NUMBER            NOT NULL, 
    USERSEQ1       NUMBER            NOT NULL, 
    USERSEQ2       NUMBER            NOT NULL, 
    CHATCONTENT    VARCHAR2(2000)    NOT NULL, 
    CHATDATE       DATE              NOT NULL, 
    CHATCHECK      VARCHAR2(20)      NOT NULL, 
    CONSTRAINT CHATTING_PK PRIMARY KEY (CHATSEQ)
);
ALTER TABLE Movie-Matching.CHATTING
    ADD CONSTRAINT FK_CHATTING_USERSEQ1_USERS_USE FOREIGN KEY (USERSEQ1)
        REFERENCES USERS (USERSEQ);

ALTER TABLE Movie-Matching.CHATTING
    ADD CONSTRAINT FK_CHATTING_USERSEQ2_USERS_USE FOREIGN KEY (USERSEQ2)
        REFERENCES USERS (USERSEQ);
        
        
        
CREATE TABLE MATCHING(
    MATCHINGSEQ          NUMBER          NOT NULL, 
    MATCHINGWRITER       NUMBER          NULL, 
    MATCHINGAPPLICANT    NUMBER          NULL, 
    MATCHINGSTATE        VARCHAR2(20)    NULL, 
    WRITERNOTICE         VARCHAR2(20)    NULL, 
    APPLICANTNOTICE      VARCHAR2(20)    NULL, 
    MATCHINGDATE         DATE            NULL, 
    SELECTEDAPPLICANT    VARCHAR2(20)    NULL, 
    CONSTRAINT MATCHING_PK PRIMARY KEY (MATCHINGSEQ)
);


--코인--
CREATE SEQUENCE COIN_SEQ;

CREATE TABLE COIN
(
    COINSEQ     NUMBER    NOT NULL, 
    USERSEQ     NUMBER    NOT NULL, 
    COINLOG     NUMBER    NOT NULL, 
    COINDATE    DATE      NOT NULL,
    COINSTATE   VARCHAR(200) NOT NULL,
    CONSTRAINT COIN_PK PRIMARY KEY (COINSEQ)
);

ALTER TABLE COIN
    ADD CONSTRAINT FK_COIN_USERSEQ FOREIGN KEY (USERSEQ)
        REFERENCES USERS (USERSEQ);
        
        
-- 리뷰보드 --
CREATE TABLE REVIEWBOARD(
REVIEWBOARDSEQ NUMBER PRIMARY KEY,
USERSEQ NUMBER NOT NULL,
MOVIETITLE VARCHAR2(200) NULL,
REVIEWBOARDTITLE VARCHAR2(200) NULL,
REVIEWBOARDCONTENT VARCHAR2(4000) NULL,
REVIEWBOARDDATE DATE NULL,
REVIEWBOARDVIEW NUMBER NOT NULL
);

CREATE SEQUENCE REVIEWBOARD_SEQ;


-- 리뷰보드 댓글  --
CREATE SEQUENCE REVIEWBOARDCOMENT_SEQ;


CREATE TABLE REVIEWBOARDCOMENT
(
    REVIEWBOARDCOMENTSEQ        NUMBER            NOT NULL, 
    REVIEWBOARDSEQ               NUMBER            NULL, 
    REVIEWBOARDCOMENTCONTENT    VARCHAR2(2000)    NULL, 
    USERNAME                      VARCHAR2(200)      NULL, 
    REVIEWBOARDCOMENTDATE       DATE              NULL,
    USERSEQ                     NUMBER       NULL,
    CONSTRAINT REVIEWBOARDCOMENT_PK PRIMARY KEY (REVIEWBOARDCOMENTSEQ)
);

ALTER TABLE REVIEWBOARDCOMENT
    ADD CONSTRAINT FK_REVIEWBOARDCOMENT FOREIGN KEY (REVIEWBOARDSEQ)
        REFERENCES REVIEWBOARD (REVIEWBOARDSEQ);

ALTER TABLE REVIEWBOARDCOMENT
    ADD CONSTRAINT FK_REVIEW_USERSEQ FOREIGN KEY (USERSEQ)
        REFERENCES USERS (USERSEQ);